# \u5E94\u7528\u670D\u52A1 WEB \u8BBF\u95EE\u7AEF\u53E3
server:
 port: 80


spring:
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  url: jdbc:mysql://localhost:3306/yunmayi?serverTimezone=UTC
  password: 1234
 redis:
  database: 0
  host: 192.168.200.100
  port: 6379
  password: 1234
  timeout: 1000



 mvc:
  pathmatch:
   matching-strategy: ant_path_matcher

mybatis-plus:
 mapper-locations: mappers/*xml
 type-aliases-package:
 configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



